from app.services import (
    assignment_service,
    athlete_service,
    backup_service,
    content_change_log_service,
    dangerous_operation_service,
    exercise_category_service,
    exercise_service,
    log_service,
    monitoring_service,
    plan_service,
    session_service,
    test_record_service,
    training_report_service,
)

__all__ = [
    "assignment_service",
    "athlete_service",
    "backup_service",
    "content_change_log_service",
    "dangerous_operation_service",
    "exercise_category_service",
    "exercise_service",
    "log_service",
    "monitoring_service",
    "plan_service",
    "session_service",
    "test_record_service",
    "training_report_service",
]
