"""baseline_schema

Revision ID: c318e7988c37
Revises: 
Create Date: 2026-04-23 09:38:55.819958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c318e7988c37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_categories',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name_zh', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('code', sa.String(length=240), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['exercise_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('parent_id', 'level', 'name_zh', name='uq_exercise_category_path')
    )
    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_categories_id'), ['id'], unique=False)

    op.create_table('sports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sports_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('exercises',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('level1_category', sa.String(length=120), nullable=True),
    sa.Column('level2_category', sa.String(length=160), nullable=True),
    sa.Column('base_movement', sa.String(length=160), nullable=True),
    sa.Column('category_path', sa.String(length=255), nullable=True),
    sa.Column('original_english_fields', sa.JSON(), nullable=True),
    sa.Column('structured_tags', sa.JSON(), nullable=True),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('tag_text', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('video_path', sa.String(length=255), nullable=True),
    sa.Column('coaching_points', sa.Text(), nullable=True),
    sa.Column('common_errors', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('default_increment', sa.Float(), nullable=True),
    sa.Column('is_main_lift_candidate', sa.Boolean(), nullable=False),
    sa.Column('base_category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['base_category_id'], ['exercise_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)

    op.create_table('teams',
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'code', name='uq_team_sport_code')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)

    op.create_table('athletes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('wingspan', sa.Float(), nullable=True),
    sa.Column('standing_reach', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletes_id'), ['id'], unique=False)

    op.create_table('exercise_tags',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'tag_id', name='uq_exercise_tag')
    )
    with op.batch_alter_table('exercise_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_tags_id'), ['id'], unique=False)

    op.create_table('training_plan_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sport_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plan_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_plan_templates_id'), ['id'], unique=False)

    op.create_table('athlete_plan_assignments',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['training_plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_plan_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_plan_assignments_id'), ['id'], unique=False)

    op.create_table('test_records',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_type', sa.String(length=80), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=False),
    sa.Column('result_text', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_records_id'), ['id'], unique=False)

    op.create_table('training_plan_template_items',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('prescribed_sets', sa.Integer(), nullable=False),
    sa.Column('prescribed_reps', sa.Integer(), nullable=False),
    sa.Column('target_note', sa.Text(), nullable=True),
    sa.Column('is_main_lift', sa.Boolean(), nullable=False),
    sa.Column('enable_auto_load', sa.Boolean(), nullable=False),
    sa.Column('initial_load_mode', sa.String(length=30), nullable=False),
    sa.Column('initial_load_value', sa.Float(), nullable=True),
    sa.Column('progression_goal', sa.String(length=30), nullable=True),
    sa.Column('progression_rules', sa.JSON(), nullable=True),
    sa.Column('ai_adjust_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['training_plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plan_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_plan_template_items_id'), ['id'], unique=False)

    op.create_table('assignment_item_overrides',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=False),
    sa.Column('initial_load_override', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['athlete_plan_assignments.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['training_plan_template_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'template_item_id', name='uq_assignment_item_override')
    )
    with op.batch_alter_table('assignment_item_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_item_overrides_id'), ['id'], unique=False)

    op.create_table('training_sessions',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coach_note', sa.Text(), nullable=True),
    sa.Column('athlete_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['athlete_plan_assignments.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['training_plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'session_date', name='uq_assignment_session_date')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_id'), ['id'], unique=False)

    op.create_table('training_session_items',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('prescribed_sets', sa.Integer(), nullable=False),
    sa.Column('prescribed_reps', sa.Integer(), nullable=False),
    sa.Column('target_note', sa.Text(), nullable=True),
    sa.Column('is_main_lift', sa.Boolean(), nullable=False),
    sa.Column('enable_auto_load', sa.Boolean(), nullable=False),
    sa.Column('initial_load', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['training_plan_template_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_session_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_session_items_id'), ['id'], unique=False)

    op.create_table('set_records',
    sa.Column('session_item_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('actual_weight', sa.Float(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=False),
    sa.Column('actual_rir', sa.Integer(), nullable=False),
    sa.Column('suggestion_weight', sa.Float(), nullable=True),
    sa.Column('suggestion_reason', sa.Text(), nullable=True),
    sa.Column('user_decision', sa.String(length=20), nullable=False),
    sa.Column('final_weight', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_item_id'], ['training_session_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_item_id', 'set_number', name='uq_session_item_set_number')
    )
    with op.batch_alter_table('set_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_records_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_records_id'))

    op.drop_table('set_records')
    with op.batch_alter_table('training_session_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_session_items_id'))

    op.drop_table('training_session_items')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_id'))

    op.drop_table('training_sessions')
    with op.batch_alter_table('assignment_item_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_item_overrides_id'))

    op.drop_table('assignment_item_overrides')
    with op.batch_alter_table('training_plan_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_plan_template_items_id'))

    op.drop_table('training_plan_template_items')
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_records_id'))

    op.drop_table('test_records')
    with op.batch_alter_table('athlete_plan_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_plan_assignments_id'))

    op.drop_table('athlete_plan_assignments')
    with op.batch_alter_table('training_plan_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_plan_templates_id'))

    op.drop_table('training_plan_templates')
    with op.batch_alter_table('exercise_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_tags_id'))

    op.drop_table('exercise_tags')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_id'))

    op.drop_table('athletes')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_code'))

    op.drop_table('exercises')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_id'))
        batch_op.drop_index(batch_op.f('ix_tags_category'))

    op.drop_table('tags')
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sports_id'))

    op.drop_table('sports')
    with op.batch_alter_table('exercise_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_categories_id'))

    op.drop_table('exercise_categories')
    # ### end Alembic commands ###
