DEFAULT_TAGS = [
    {"category": "body_part", "name": "上肢", "code": "body-upper", "color": "#2563eb", "sort_order": 1, "is_system": True},
    {"category": "body_part", "name": "下肢", "code": "body-lower", "color": "#16a34a", "sort_order": 2, "is_system": True},
    {"category": "body_part", "name": "核心", "code": "body-core", "color": "#ca8a04", "sort_order": 3, "is_system": True},
    {"category": "body_part", "name": "全身", "code": "body-full", "color": "#7c3aed", "sort_order": 4, "is_system": True},
    {"category": "direction", "name": "推", "code": "dir-push", "color": "#dc2626", "sort_order": 1, "is_system": True},
    {"category": "direction", "name": "拉", "code": "dir-pull", "color": "#0891b2", "sort_order": 2, "is_system": True},
    {"category": "direction", "name": "旋转", "code": "dir-rotate", "color": "#9333ea", "sort_order": 3, "is_system": True},
    {"category": "direction", "name": "抗旋转", "code": "dir-anti-rotate", "color": "#0f766e", "sort_order": 4, "is_system": True},
    {"category": "attribute", "name": "力量", "code": "attr-strength", "color": "#b91c1c", "sort_order": 1, "is_system": True},
    {"category": "attribute", "name": "功率", "code": "attr-power", "color": "#ea580c", "sort_order": 2, "is_system": True},
    {"category": "attribute", "name": "速度", "code": "attr-speed", "color": "#2563eb", "sort_order": 3, "is_system": True},
    {"category": "attribute", "name": "稳定", "code": "attr-stability", "color": "#15803d", "sort_order": 4, "is_system": True},
    {"category": "ssc", "name": "快速 SSC", "code": "ssc-fast", "color": "#1d4ed8", "sort_order": 1, "is_system": True},
    {"category": "ssc", "name": "慢速 SSC", "code": "ssc-slow", "color": "#6d28d9", "sort_order": 2, "is_system": True},
    {"category": "ssc", "name": "非 SSC", "code": "ssc-none", "color": "#475569", "sort_order": 3, "is_system": True},
    {"category": "purpose", "name": "主项", "code": "purpose-main", "color": "#be123c", "sort_order": 1, "is_system": True},
    {"category": "purpose", "name": "辅助", "code": "purpose-assist", "color": "#0f766e", "sort_order": 2, "is_system": True},
    {"category": "purpose", "name": "激活", "code": "purpose-activate", "color": "#2563eb", "sort_order": 3, "is_system": True},
    {"category": "purpose", "name": "预康复", "code": "purpose-prehab", "color": "#65a30d", "sort_order": 4, "is_system": True},
    {"category": "joint", "name": "踝", "code": "joint-ankle", "color": "#ea580c", "sort_order": 1, "is_system": True},
    {"category": "joint", "name": "膝", "code": "joint-knee", "color": "#ef4444", "sort_order": 2, "is_system": True},
    {"category": "joint", "name": "髋", "code": "joint-hip", "color": "#16a34a", "sort_order": 3, "is_system": True},
    {"category": "joint", "name": "肩", "code": "joint-shoulder", "color": "#0ea5e9", "sort_order": 4, "is_system": True},
    {"category": "joint", "name": "核心", "code": "joint-core", "color": "#7c3aed", "sort_order": 5, "is_system": True},
]

DEFAULT_EXERCISES = [
    {
        "name": "深蹲",
        "alias": "杠铃深蹲",
        "description": "发展下肢力量和整体支撑能力的主项动作。",
        "video_url": "https://example.com/videos/squat",
        "video_path": None,
        "coaching_points": "吸气撑腹，髋膝同步下沉，脚掌全脚掌发力。",
        "common_errors": "膝内扣、塌腰、下蹲深度不足。",
        "notes": "适合作为下肢力量主项。",
        "load_profile": "squat",
        "default_increment": 5.0,
        "is_main_lift_candidate": True,
        "tag_codes": ["body-lower", "dir-push", "attr-strength", "ssc-slow", "purpose-main", "joint-knee", "joint-hip"],
    },
    {
        "name": "卧推",
        "alias": "杠铃卧推",
        "description": "发展上肢水平推力量的主项动作。",
        "video_url": "https://example.com/videos/bench",
        "video_path": None,
        "coaching_points": "肩胛收紧，下背自然弓起，杠铃稳定下降到下胸。",
        "common_errors": "肩部耸起、手腕后翻、发力不对称。",
        "notes": "适合作为上肢力量主项。",
        "load_profile": "push",
        "default_increment": 2.5,
        "is_main_lift_candidate": True,
        "tag_codes": ["body-upper", "dir-push", "attr-strength", "ssc-slow", "purpose-main", "joint-shoulder"],
    },
    {
        "name": "硬拉",
        "alias": "传统硬拉",
        "description": "发展后侧链力量和整体拉力能力的主项动作。",
        "video_url": "https://example.com/videos/deadlift",
        "video_path": None,
        "coaching_points": "背部保持中立，杠铃贴腿上拉，髋部主动发力。",
        "common_errors": "弓背起拉、杠铃离腿、锁定阶段后仰过度。",
        "notes": "适合作为拉类力量主项。",
        "load_profile": "pull",
        "default_increment": 5.0,
        "is_main_lift_candidate": True,
        "tag_codes": ["body-lower", "dir-pull", "attr-strength", "ssc-slow", "purpose-main", "joint-hip", "joint-core"],
    },
    {
        "name": "罗马尼亚硬拉",
        "alias": "RDL",
        "description": "强化腘绳肌和臀部离心控制。",
        "video_url": "https://example.com/videos/rdl",
        "video_path": None,
        "coaching_points": "屈髋后移，杠铃贴腿，下放到腘绳肌拉伸明显即可。",
        "common_errors": "弓背、膝盖前顶、下放过深失去控制。",
        "notes": "适合作为后侧链辅助动作。",
        "load_profile": "pull",
        "default_increment": 5.0,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-lower", "dir-pull", "attr-strength", "purpose-assist", "joint-hip"],
    },
    {
        "name": "哑铃推举",
        "alias": "坐姿推举",
        "description": "发展肩部稳定和垂直推能力。",
        "video_url": "https://example.com/videos/db-press",
        "video_path": None,
        "coaching_points": "核心收紧，手肘略在杠铃下方，向上推到头顶上方。",
        "common_errors": "耸肩、腰椎过度代偿、推举路径偏移。",
        "notes": "上肢辅助动作。",
        "load_profile": "push",
        "default_increment": 2.0,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-upper", "dir-push", "attr-strength", "purpose-assist", "joint-shoulder"],
    },
    {
        "name": "引体向上",
        "alias": "高位自重拉",
        "description": "发展上肢垂直拉力量。",
        "video_url": "https://example.com/videos/pull-up",
        "video_path": None,
        "coaching_points": "肩胛先下沉，胸口主动靠近横杆，全程保持身体稳定。",
        "common_errors": "摆动借力、下巴硬抬、下放不受控。",
        "notes": "上肢拉类辅助动作。",
        "load_profile": "pull",
        "default_increment": 2.5,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-upper", "dir-pull", "attr-strength", "purpose-assist", "joint-shoulder"],
    },
    {
        "name": "保加利亚分腿蹲",
        "alias": "分腿蹲",
        "description": "发展单腿力量和骨盆稳定。",
        "video_url": "https://example.com/videos/split-squat",
        "video_path": None,
        "coaching_points": "前脚全脚掌发力，躯干保持稳定，髋部正向朝前。",
        "common_errors": "前膝内扣、上体过度前倾、后腿借力过多。",
        "notes": "下肢辅助动作。",
        "load_profile": "squat",
        "default_increment": 2.5,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-lower", "dir-push", "attr-strength", "purpose-assist", "joint-knee", "joint-hip"],
    },
    {
        "name": "箱跳",
        "alias": "跳箱",
        "description": "发展下肢快速 SSC 和爆发能力。",
        "video_url": "https://example.com/videos/box-jump",
        "video_path": None,
        "coaching_points": "快速摆臂起跳，落地缓冲稳定，保持安静落地。",
        "common_errors": "落地僵硬、塌腰、箱高选择过高。",
        "notes": "速度力量动作。",
        "load_profile": "general",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-lower", "attr-power", "attr-speed", "ssc-fast", "purpose-main", "joint-ankle", "joint-knee"],
    },
    {
        "name": "药球胸前传",
        "alias": "药球爆发推",
        "description": "发展上肢快速出力和爆发传递。",
        "video_url": "https://example.com/videos/medball-chest-pass",
        "video_path": None,
        "coaching_points": "站姿稳定，胸前快速发力，球出手后保持身体平衡。",
        "common_errors": "肩膀耸起、发力拖沓、躯干后仰过多。",
        "notes": "上肢功率动作。",
        "load_profile": "push",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-upper", "dir-push", "attr-power", "attr-speed", "ssc-fast", "purpose-main", "joint-shoulder"],
    },
    {
        "name": "平板支撑",
        "alias": "前平板",
        "description": "强化核心抗伸展稳定。",
        "video_url": "https://example.com/videos/plank",
        "video_path": None,
        "coaching_points": "肋骨下沉，臀部夹紧，头颈保持中立。",
        "common_errors": "塌腰、臀部抬太高、耸肩。",
        "notes": "核心稳定动作。",
        "load_profile": "general",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-core", "dir-anti-rotate", "attr-stability", "ssc-none", "purpose-assist", "joint-core"],
    },
    {
        "name": "侧桥",
        "alias": "侧向支撑",
        "description": "发展核心侧向稳定与抗侧屈能力。",
        "video_url": "https://example.com/videos/side-plank",
        "video_path": None,
        "coaching_points": "躯干成一直线，髋部主动顶起，肩肘垂直。",
        "common_errors": "身体塌陷、肩膀疼痛代偿、头颈不稳定。",
        "notes": "核心辅助动作。",
        "load_profile": "general",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-core", "dir-anti-rotate", "attr-stability", "ssc-none", "purpose-assist", "joint-core"],
    },
    {
        "name": "滑板腿弯举",
        "alias": "腘绳肌滑行",
        "description": "提升腘绳肌离心控制和膝关节保护能力。",
        "video_url": "https://example.com/videos/hamstring-curl",
        "video_path": None,
        "coaching_points": "骨盆稳定，缓慢伸腿再主动拉回。",
        "common_errors": "腰部代偿、髋部下沉、动作速度失控。",
        "notes": "预康复动作。",
        "load_profile": "general",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-lower", "attr-stability", "purpose-prehab", "joint-knee", "joint-hip"],
    },
    {
        "name": "踝关节弹跳",
        "alias": "脚踝小跳",
        "description": "提升踝关节弹性与快速 SSC 表现。",
        "video_url": "https://example.com/videos/ankle-hop",
        "video_path": None,
        "coaching_points": "触地时间短，躯干稳定，脚踝主动发力。",
        "common_errors": "膝盖参与过多、落地声音大、节奏不稳定。",
        "notes": "下肢激活动作。",
        "load_profile": "general",
        "default_increment": None,
        "is_main_lift_candidate": False,
        "tag_codes": ["body-lower", "attr-speed", "ssc-fast", "purpose-activate", "joint-ankle"],
    },
]
